_commit: v1.0.2
_src_path: /home/ko/ghq/github.com/Kololu777/playground/copir-practice/templates/pyproj-template/
authors:
-   email: taro@example.com
    name: Taco Taro
docs_tool: mkdocs
license: MIT
linters:
- ruff
project_name: Doc Proj
project_slug: doc_proj
use_docs: true
