name: PR to main hello

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo hello